### ISSUE TITLE
analysis won't start on a VM?

### ISSUE THREAD

**Issue by JustinWebDev** [fifonik/FFMetrics#35] opened 2021-05-06 23:23 UTC
I tried to run the app on a VirtualBox VM and the start button would never enable.  No error conditions or log file.

**Comment by fifonik** [comment] 2021-05-07 12:54
I never tried to run the program in VM.
After your report I tried to do this in Hyper-X supervisor on my Win 10 Pro 2004 PC with Win 10 Enterprise Evaluation 1809 guest OS (downloaded MS Edge Win 10 VM downloaded from Microsoft Web site).
No issues here.

![image](https://user-images.githubusercontent.com/7234987/117452471-261fdc00-af87-11eb-986f-b9cc092fb9a3.png)


So, I'd suggest you to do the following::
- Run the program
- Enable option "Write FFMpeg commands in log"
- Close program
- Delete FFMetrics.log
- Run program with option -log-level=debug
- Add ref file
- Add one distorted file
- Click Run button if possible
- Take screenshot
- Close the program
- Provide screenshot and FFMetrics.log

**Comment by JustinWebDev** [comment] 2021-05-17 00:13
Again, the Start button would not react, but I did get a log.
![image](https://user-images.githubusercontent.com/40804543/118417665-cad2a580-b67a-11eb-9a6c-f69a25bd8163.png)
[FFMetrics.log](https://github.com/fifonik/FFMetrics/files/6490321/FFMetrics.log)

**Comment by fifonik** [comment] 2021-05-17 07:18
Based on log you provided, I think the issue is caused by your **ts** file.
You can check it out issuing the following command directly:
`ffmpeg -hide_banner -i "Y:\MCEBuddy_done\Dances with Wolves (1990).ts" -frames:v 60 -filter:v idet -f null -`
ffmpeg reported:

> [mpeg2video @ 000002bfa45f4300] Invalid frame dimensions 0x0.
>     Last message repeated 17 times
> [mpegts @ 000002bfa45ed600] PES packet size mismatch
> [mpegts @ 000002bfa45ed600] Packet corrupt (stream = 1, dts = 1252418454).
> Input #0, mpegts, from 'Y:\MCEBuddy_done\Dances with Wolves (1990).ts':
>   Duration: 01:59:50.99, start: 6725.360600, bitrate: 6349 kb/s
>   Program 6 
>   Stream #0:0[0x81]: Video: mpeg2video (Main) ([2][0][0][0] / 0x0002), yuv420p(tv, progressive), 1280x720 [SAR 1:1 DAR 16:9], Closed Captions, 59.94 fps, 59.94 tbr, 90k tbn, 119.88 tbc
>     Side data:
>       cpb: bitrate max/min/avg: 14652800/0/0 buffer size: 7995392 vbv_delay: N/A
>   Stream #0:1[0x84](eng): Audio: ac3 (AC-3 / 0x332D4341), 48000 Hz, stereo, fltp, 192 kb/s
> Stream mapping:
>   Stream #0:0 -> #0:0 (mpeg2video (native) -> wrapped_avframe (native))
>   Stream #0:1 -> #0:1 (ac3 (native) -> pcm_s16le (native))
> Press [q] to stop, [?] for help
> Output #0, null, to 'pipe:':
>   Metadata:
>     encoder         : Lavf58.76.100
>   Stream #0:0: Video: wrapped_avframe, yuv420p(tv, progressive), 1280x720 [SAR 1:1 DAR 16:9], q=2-31, 200 kb/s, 59.94 fps, 59.94 tbn
>     Metadata:
>       encoder         : Lavc58.134.100 wrapped_avframe
>   Stream #0:1(eng): Audio: pcm_s16le, 48000 Hz, stereo, s16, 1536 kb/s
>     Metadata:
>       encoder         : Lavc58.134.100 pcm_s16le
> frame=    1 fps=0.0 q=-0.0 size=N/A time=00:00:00.98 bitrate=N/A speed= 212x    
> frame=   60 fps=0.0 q=-0.0 Lsize=N/A time=00:00:01.96 bitrate=N/A speed=24.8x    
> video:31kB audio:294kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
> [Parsed_idet_0 @ 000002bfa4c47240] Repeated Fields: Neither:    61 Top:     0 Bottom:     0
> [Parsed_idet_0 @ 000002bfa4c47240] Single frame detection: TFF:     0 BFF:     0 Progressive:    57 Undetermined:     4
> [Parsed_idet_0 @ 000002bfa4c47240] Multi frame detection: TFF:     0 BFF:     0 Progressive:    60 Undetermined:     1

However, as you can see somehow it is still reporting back something useful.

Without having file with such issue it would be hard to handle such situations properly (I'm still trying to think of a proper solution). If you can share the file -- please do so and sent me a link in PM or by email.

Thanks.

**Comment by JustinWebDev** [comment] 2021-05-18 00:12
It is not the TS file.  All my files did the same thing, and it never happened on my host machine.
I fixed it by renaming the config file (forcing it to be recreated) and I could run an analysis.  Config files attached.

BTW, I found that if you kill FFMetrics while an analysis is running, FFMpeg continues to run.

**Comment by fifonik** [comment] 2021-05-18 01:56
Based on configs you provided, you have not chosen any Metrics to calculate (as I suggested at very beginning of my previous message, that is in bold).

No any metric selected -- nothing to calculate. So at least one metric must be selected:
![image](https://user-images.githubusercontent.com/7234987/118578680-ebf8da80-b7cf-11eb-9cc9-874e796fe5e3.png)

It was a bug in one of the previous version when during first program run there were no metrics selected. It was fixed in the following version, however in your case this was probably saves in your settings or project file.

**Comment by JustinWebDev** [comment] 2021-05-18 21:46
Quite right.  I restored the bad config file, selected a metric, and the button enabled.  Wow.  I don't know how all those were deselected, as I wasn't even familiar with those settings until later.  Either way, sorry for the bother, and thanks for the help!

**Closed** 2021-05-19 02:50 UTC
