### ISSUE TITLE
Failing to find ffmpeg

### ISSUE THREAD

**Issue by thirteenwings** [fifonik/FFMetrics#122] opened 2023-09-07 09:13 UTC
On Windows 10. Ffmpeg version 6.0 stable.
Tried using 1.3.1 -- after the initial scan no ffmpeg version is shown. Program still tries to scan media files, no metadata shows. Buttons are inactive.
Tried using 1,4.8 beta, it's spent 5 mins on getting ffmpeg version and is still going.
In a command prompt, ffmpeg -version shows:
ffmpeg version 6.0-full_build-www.gyan.dev Copyright (c) 2000-2023 the FFmpeg developers
built with gcc 12.2.0 (Rev10, Built by MSYS2 project)

**Comment by thirteenwings** [comment] 2023-09-07 11:39
[CrashDumps.zip](https://github.com/fifonik/FFMetrics/files/12548175/CrashDumps.zip)

Program crashes when I start with -log-level=debug. First 2 dumps are 1.4.8, last 2 are 1.3.1.

**Comment by thirteenwings** [comment] 2023-09-07 17:22
Okay, so here's what I've tried:
1. Moved FFMetrics to a different folder with r/w permissions. This fixed the crashing and I got a logfile. However, the logfile said:
2023-09-07 22:52:18	DEBUG: Started
2023-09-07 22:52:18	DEBUG: Initialize finished
2023-09-07 22:52:18	DEBUG: .NET version detected: 480
2023-09-07 22:52:18	DEBUG: InitializeProgramConfig started
2023-09-07 22:52:18	DEBUG: InitializeProgramConfig finished
2023-09-07 22:52:18	DEBUG: InitializeWorkers started
2023-09-07 22:52:18	DEBUG: InitializeWorkers finished
2023-09-07 22:52:18	DEBUG: InitializeCommands started
2023-09-07 22:52:18	DEBUG: InitializeCommands finished
2023-09-07 22:52:18	DEBUG: FF.VersionInfoGet.Started
2023-09-07 22:52:18	ffmpeg.exe -nostdin -filters
2023-09-07 22:52:18	DEBUG: FF.ExecStatus.Started, -nostdin -filters
2023-09-07 22:52:28	DEBUG: FF.ExecStatus.Finished. stdout: , stderr: The system cannot find the file specified(-1)
2023-09-07 22:52:28	DEBUG: FF.VersionInfoGet.Finished: OK
2023-09-07 22:53:48	DEBUG: Finished

2. I also tried moving the ffmpeg folder. Same result.
3. When I run "ffmpeg -nostdin -filters" in a command prompt, I get an output as in attachment ffmpeg-output.txt

FFMetrics is still failing to load the ffmpeg version, the tooltip says "The system cannot find the file specified"
[FFMetrics.log](https://github.com/fifonik/FFMetrics/files/12551856/FFMetrics.log)
[ffmpeg-output.txt](https://github.com/fifonik/FFMetrics/files/12551858/ffmpeg-output.txt)

**Comment by fifonik** [comment] 2023-09-07 21:43
"The system cannot find the file specified" means exactly what it says.
FFMetrics is trying to execute ffmpeg.exe without providing any path.
This must work if ffmpeg.exe (and accompanied dlls if you use shared build) is located in program directory (aside of ffmetrics.exe) or in system %path%.

So:
1. What type of ffmpeg you use -- shared (exe + dlls) or static (single exe)?
2. Where ffmpeg.exe located -- directly in ...\FFMetrics\ dir aside of ffmetrics.exe or somewhere else?
3. If it is located **not** in ...\FFMetrics\ dir, then does the ffmpeg's dir is in the %PATH%? Have you double checked it?
4. When you moved ffmpeg folder as you mentioned, have you adjusted system %PATH%?

For simplicity I'd recommend to download static ffmpeg build and put it inside ...\FFMetrics\ dir, just aside of ffmetrics.exe

**Comment by thirteenwings** [comment] 2023-09-08 02:28
Hi. I just woke up and had a thought while having coffee. I tried running it with admin privileges, and it's working now. I'm not sure if that's in the instructions somewhere and I missed it, but it's here now in case anyone else runs into the same issue.

**Comment by fifonik** [comment] 2023-09-08 08:59
Hm.
Everything should work without admin privileges and it works in my case.

**Comment by tormento** [comment] 2024-06-28 19:11
I have almost the same problem.

On some runs, it fails to recognize ffmpeg capabilities. Thus start is disabled.

Until now I simply launched it once, closed it and launched a second time but someone else is having a similar problem so I decided to finally report.

**Comment by fifonik** [comment] 2024-06-28 23:02
The same question: have you followed troubleshooting steps?

Have you tried to follow [this](https://github.com/fifonik/FFMetrics/issues/122#issuecomment-1710805716)?

**Comment by tormento** [comment] 2024-06-29 11:00
> Have you tried to follow this?

I can't complete the analyze step as FFMetrics can't find ffmpeg capabilities.

1. Tried both static and dynamic, both stable and nightly, both BtbN and GyanD.
2. FFMpeg is in FFMetrics directory

Log:

```
2024-06-29 12:55:49	DEBUG: Started
2024-06-29 12:55:49	DEBUG: Initialize finished
2024-06-29 12:55:49	DEBUG: .NET version detected: 480
2024-06-29 12:55:49	DEBUG: InitializeProgramConfig started
2024-06-29 12:55:49	DEBUG: InitializeProgramConfig finished
2024-06-29 12:55:49	DEBUG: InitializeWorkers started
2024-06-29 12:55:49	DEBUG: InitializeWorkers finished
2024-06-29 12:55:49	DEBUG: InitializeCommands started
2024-06-29 12:55:49	DEBUG: InitializeCommands finished
2024-06-29 12:55:50	DEBUG: FF.VersionInfoGet.Started
2024-06-29 12:55:50	ffmpeg -nostdin -filters
2024-06-29 12:55:50	DEBUG: FF.ExecStatus.Started, -nostdin -filters
2024-06-29 12:55:55	DEBUG: FF.ExecStatus: External program not exited, trying to close it
2024-06-29 12:55:55	DEBUG: FF.ExecStatus: External program closing failed. Killing it
2024-06-29 12:56:03	DEBUG: FF.ExecStatus.Finished. stdout: , stderr: Timed out(-2)
2024-06-29 12:56:03	DEBUG: FF.VersionInfoGet.Finished: OK
2024-06-29 12:56:37	DEBUG: Finished
```

**Comment by fifonik** [comment] 2024-06-29 11:32
I was referring to option `--debug` and providing log.
As I see from the log, "ffmpeg -nostdin -filters" not finished in 5 seconds, so timed out.

Some things to consider/investigate:
- Usually dynamic build faster on consecutive runs, but in this case it is the first ffmpeg's run so this will not help;
- Antivirus. You can try to add ffmpeg.exe (**not ffmetrics.exe**) into AV exceptions;
- ffmpeg is located on HDD that is in sleep. You can move ffmpeg to system drive (preferably SSD) and adjust system %path%;
- System is slow. You can try to increase timeout using FFMetrics.conf: `{"VersionInfo": {"Timeout": 10000}}`

I do not have any other ideas now, unfortunately.

**Comment by fifonik** [comment] 2024-07-25 09:07
HAve you tried to follow suggestions I posted in this thread?

**Comment by tormento** [comment] 2024-07-25 10:54
@fifonik too much people is having the very same problem.

If we can help to debug, ask.

It appears every single time that I launch it, after some time I didn't.

At the second launch, it works perfectly.

I have other programs using ffmpeg and ffprobe and none has the same behaviour.

**Comment by fifonik** [comment] 2024-07-26 07:07
Just add a timeout as I mentioned. If this fix the issue, I can change in-build timeout.

> I have other programs using ffmpeg and ffprobe and none have the same behaviour.

I cannot discuss unknown programs with unknown behaviour, sorry.
If I remove feature checks at the program startup it will be no such issues at all during startup and during metrics  calculating (timeout is much bigger for that operation).
However, some issues may appear when user click 'Run' button such as: no selected model, ffmpeg not found, etc.
So I decided to do all checks on startup.

**Comment by fifonik** [comment] 2024-07-26 07:09
> too much people is having the very same problem.

Are you sure that the issue is the same?
I have not seen any technical details provided for the last case and my crystal ball is broken at this moment.

**Comment by fifonik** [comment] 2024-10-19 09:33
I've increased ffmpeg version check timeout on startup from 5 to 10 seconds.

**Comment by tormento** [comment] 2024-10-19 10:51
Thanks for your last build.

Tried it but unfortunately nothing changed. I had to run twice to have ffmpeg to be properly recognized.

After the second run, on every subsequent opening it works until a sort of "timeout": after a few hours I had to run it twice again.

Funny part: before installing your last version, I run previous FFMetrics to test the AVS HBD issue and it worked as usual.

After a couple of minutes, I tried your last one and again I had to run it twice, even if I had just used the previous one.

I am using ffmpeg shared version but I don't think that it can be the issue, as previously I used the static one.

**Comment by fifonik** [comment] 2024-10-20 02:44
I've further increased timeouts in 1.5.0 beta 10 that might help.
Unfortunately, there is no guarantee as I was not able to re-produce the issue.

**Comment by tormento** [comment] 2024-10-20 09:27
Can't you simply allow us to set the timeout?

**Comment by fifonik** [comment] 2024-10-20 09:30
What do you mean? You can do this for ages.
I've even suggested to increase the timeout in this thread: https://github.com/fifonik/FFMetrics/issues/122#issuecomment-2198113324

**Comment by tormento** [comment] 2024-10-20 09:32
Sorry, I read GitHub notifications in reverse order. I saw and thanked you.

**Comment by fifonik** [comment] 2024-12-03 07:18
Closing the issue.
If someone still have it -- create a new issue please (with details).

**Closed by fifonik** 2024-12-03 07:18 UTC
Labels: help wanted
