### ISSUE TITLE
VMAF score error

### ISSUE THREAD

**Issue by ShiftyDC** [fifonik/FFMetrics#7] opened 2020-11-08 15:59 UTC
OS: Win 10 19042.610
FFMPEG ver.: 4.3.1
![Snímek obrazovky 2020-11-08 165648](https://user-images.githubusercontent.com/74143499/98470089-c6b55f00-21e3-11eb-9fe5-32248ba4db93.png)

**Comment by FireCulex** [comment] 2020-11-08 20:05
Same here.
2020-11-08 12:05:19	ERROR: D:\videos\testing\sub\1080p30_30qp.mkv: Object reference not set to an instance of an object.

**Comment by fifonik** [comment] 2020-11-09 05:50
- Tick "Log FFMpeg commands" checkbox
- Untick PSNR & SSIM, tick VMAF
- Close program
- Delete FFMetrics.log
- Run program & click Start
- Open FFMetrics.log and check the last executed FFMpeg command
- Run the command from command prompt
- Provide the command (copy/paste it from log) and the end of FFMpeg output (screenshot)

Thanks.

**Comment by ShiftyDC** [comment] 2020-11-09 11:11
> 
> 
>     * Tick "Log FFMpeg commands" checkbox
> 
>     * Untick PSNR & SSIM, tick VMAF
> 
>     * Close program
> 
>     * Delete FFMetrics.log
> 
>     * Run program & click Start
> 
>     * Open FFMetrics.log and check the last executed FFMpeg command
> 
>     * Run the command from command prompt
> 
>     * Provide the command (copy/paste it from log) and the end of FFMpeg output (screenshot)
> 
> 
> Thanks.

I did everything and this is the output
![CMD_log](https://user-images.githubusercontent.com/74143499/98534387-aee1e780-2284-11eb-85bf-0923733deff8.png)

**Comment by ShiftyDC** [comment] 2020-11-09 11:12
Last command in FFMetrics.log was this:
ffmpeg.exe -hide_banner -nostdin -i "D:/OneDrive - Office Everyday/ČVUT/2. ročník/MOT/VMAF - Semestralni projekt/Video database/Mobile/PXL_HEVC_LOW.mp4" -i "D:/OneDrive - Office Everyday/ČVUT/2. ročník/MOT/VMAF - Semestralni projekt/Video database/Mobile/PXL_ref.mp4" -lavfi "[0:v]setpts=PTS-STARTPTS[main];[1:v]setpts=PTS-STARTPTS[ref];[main][ref]libvmaf='eof_action=endall:phone_model=0:pool=mean:model_path=D\:/OneDrive - Office Everyday/ČVUT/2. ročník/MOT/VMAF - Semestralni projekt/MAINs/01 MAIN FFMETRICS/vmaf-models/vmaf_v0.6.1.pkl:log_fmt=json:log_path=C\:/Users/adams/AppData/Local/Temp/FFMetrics/PXL_HEVC_LOW.mp4_38def1c6-f99d-4c53-a84e-4f328275073d.log'" -f null -

**Comment by fifonik** [comment] 2020-11-09 12:19
I think the issue caused by special characters in model's file path (Č & Co) or its length.

FFMetrics successfully checked model file existsance, but looks like libvmaf still unable to open it. 
Could you please copy folder vmaf-models with all content close to the drive's root (D:\Temp\vmaf-models should do the trick) and try to run directly the following command:

```
ffmpeg.exe -hide_banner -nostdin -i "D:/OneDrive - Office Everyday/ČVUT/2. ročník/MOT/VMAF - Semestralni projekt/Video database/Mobile/PXL_HEVC_LOW.mp4" -i "D:/OneDrive - Office Everyday/ČVUT/2. ročník/MOT/VMAF - Semestralni projekt/Video database/Mobile/PXL_ref.mp4" -lavfi "[0:v]setpts=PTS-STARTPTS[main];[1:v]setpts=PTS-STARTPTS[ref];[main][ref]libvmaf='eof_action=endall:phone_model=0:pool=mean:model_path=D:/Temp/vmaf-models/vmaf_v0.6.1.pkl:log_fmt=json:log_path=C:/Users/adams/AppData/Local/Temp/FFMetrics/PXL_HEVC_LOW.mp4_38def1c6-f99d-4c53-a84e-4f328275073d.log'" -f null -
```

Thanks.

**Comment by ShiftyDC** [comment] 2020-11-09 16:54
> 
> 
> I think the issue caused by special characters in model's file path (Č & Co) or its length.
> 
> FFMetrics successfully checked model file existsance, but looks like libvmaf still unable to open it.
> Could you please copy folder vmaf-models with all content close to the drive's root (D:\Temp\vmaf-models should do the trick) and try to run directly the following command:
> 
> ```
> ffmpeg.exe -hide_banner -nostdin -i "D:/OneDrive - Office Everyday/ČVUT/2. ročník/MOT/VMAF - Semestralni projekt/Video database/Mobile/PXL_HEVC_LOW.mp4" -i "D:/OneDrive - Office Everyday/ČVUT/2. ročník/MOT/VMAF - Semestralni projekt/Video database/Mobile/PXL_ref.mp4" -lavfi "[0:v]setpts=PTS-STARTPTS[main];[1:v]setpts=PTS-STARTPTS[ref];[main][ref]libvmaf='eof_action=endall:phone_model=0:pool=mean:model_path=D:/Temp/vmaf-models/vmaf_v0.6.1.pkl:log_fmt=json:log_path=C:/Users/adams/AppData/Local/Temp/FFMetrics/PXL_HEVC_LOW.mp4_38def1c6-f99d-4c53-a84e-4f328275073d.log'" -f null -
> ```
> 
> Thanks.

I tried that but with the same result
![VMAF_error](https://user-images.githubusercontent.com/74143499/98571175-8bcf2c00-22b4-11eb-94b0-8f298ecb3f8e.png)

**Comment by fifonik** [comment] 2020-11-09 22:06
Run `ffmpeg` in command line and provide the output please.


On 10/11/2020, ShiftyDC <notifications@github.com> wrote:
>>

>>

>> I think the issue caused by special characters in model's file path (Č &
>> Co) or its length.

>>

>> FFMetrics successfully checked model file existsance, but looks like
>> libvmaf still unable to open it.

>> Could you please copy folder vmaf-models with all content close to the
>> drive's root (D:\Temp\vmaf-models should do the trick) and try to run
>> directly the following command:

>>

>> ```

>> ffmpeg.exe -hide_banner -nostdin -i "D:/OneDrive - Office Everyday/ČVUT/2.
>> ročník/MOT/VMAF - Semestralni projekt/Video
>> database/Mobile/PXL_HEVC_LOW.mp4" -i "D:/OneDrive - Office
>> Everyday/ČVUT/2. ročník/MOT/VMAF - Semestralni projekt/Video
>> database/Mobile/PXL_ref.mp4" -lavfi
>> "[0:v]setpts=PTS-STARTPTS[main];[1:v]setpts=PTS-STARTPTS[ref];[main][ref]libvmaf='eof_action=endall:phone_model=0:pool=mean:model_path=D:/Temp/vmaf-models/vmaf_v0.6.1.pkl:log_fmt=json:log_path=C:/Users/adams/AppData/Local/Temp/FFMetrics/PXL_HEVC_LOW.mp4_38def1c6-f99d-4c53-a84e-4f328275073d.log'"
>> -f null -

>> ```

>>

>> Thanks.

>

> I tried that but with the same result

> ![VMAF_error](https://user-images.githubusercontent.com/74143499/98571175-8bcf2c00-22b4-11eb-94b0-8f298ecb3f8e.png)

>

>

> --

> You are receiving this because you commented.

> Reply to this email directly or view it on GitHub:

> https://github.com/fifonik/FFMetrics/issues/7#issuecomment-724139278


-- 
Michael Petrushin

**Comment by FireCulex** [comment] 2020-11-10 04:24
I downloaded ffmpeg version 4.3.1-2020-11-08-full_build-www.gyan.dev and it solved my issue. 
I had ffmpeg version N-93075-gb429c86d84.

I admit I skipped over the requirements section. Might I suggest a message to update ffmpeg or better yet have the program download the binary for you and not rely on a system wide install.

**Comment by fifonik** [comment] 2020-11-10 06:03
Hm. FFMetrics should check if VMAF is supported by the ffmpeg found.
If not VMAF is supported, message "VMAF not supported" should be displayed and VMAF checkbox must be disabled.
I tried 4.2.1 and everything works as it should.
So looks like it is a bug somewhere.

Is it <a href="https://github.com/BtbN/FFmpeg-Builds">BtbN's build</a>?
What package? 

Thanks.

**Comment by fifonik** [comment] 2020-11-10 08:12
> the program download the binary for you and not rely on a system wide install.

I do not like when programs downloading the same dependencies over and over and storing them in different places on disk. 
So will not implement it. Sorry.

**Comment by FireCulex** [comment] 2020-11-10 15:45
> 
> 
> > the program download the binary for you and not rely on a system wide install.
> 
> I do not like when programs downloading the same dependencies over and over and storing them in different places on disk.
> So will not implement it. Sorry.

 It's not about downloading the same dependencies more than once but isolating the environment. Like virtualenv python in cloud apps.  Audacity you have to specifically locate the ffmpeg binary, it will not use the system wide install.  OBS comes bundled with ffmpeg. 

12 factor app - "do not rely on the implicit existence of any system tools"
"While these tools may exist on many or even most systems, there is no guarantee that they will exist on all systems where the app may run in the future, or whether the version found on a future system will be compatible with the app."

**Comment by BtbN** [comment] 2020-11-10 17:07
It's a bit of an oddity in the ffmpeg build system itself.
The vmaf based filters only get built if libvmad and pthreads are available.
So evan if you build with --enable-libvmaf you can end up without the vmaf filters, unless the build is also done with pthreads instead of w32threads. No error will be thrown either, since the libvmaf configure option is successfully enabled, and that's all configure cares about.

**Comment by fifonik** [comment] 2020-11-11 05:58
Looks like I have to check if pthreads are enabled or try to parse the first calculation output and if "No such filter: 'libvmaf'" returned, fall back to "VMAF not enabled".

**Comment by BtbN** [comment] 2020-11-11 12:55
Why not just parse the filter list for the actual filter?

**Comment by fifonik** [comment] 2020-11-12 05:53
I did not know that. Sure will do. Thanks.

**Comment by fifonik** [comment] 2020-12-03 07:48
Should be fixed in version 0.8.7b

**Closed** 2020-12-03 07:49 UTC

**Comment by megapro17** [comment] 2020-12-23 16:44
i got the same error in 0.8.7b

**Comment by fifonik** [comment] 2020-12-23 20:55
Please, provide a screenshot with execution command from command line as I mentioned [earlier](https://github.com/fifonik/FFMetrics/issues/7#issuecomment-723773400)
